### ISSUE TITLE
Migration to Nextcord Tracker

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/jct-discord-bot#316]
The bot will stop working in less than 2 months if the library is not updated.
Discord.py 1.7.3 used Discord API v7 which will be decommissioned on April 30.
To use the latest version of the API, a maintained lib such as nextcord or disnake should be used.

A [new branch](https://github.com/DenverCoder1/jct-discord-bot/tree/migrate-nextcord) has been created for the migration since there are many tasks.

- [x] Change requirements.txt and imports from discord.py to nextcord (https://github.com/DenverCoder1/jct-discord-bot/commit/cd8b39c0b060cda935ec265e10ac8830de4ee6ca)
- [x] Migrate commands to use nextcord slash instead of discord-py-slash-command
	- [x] Calendar commands (https://github.com/DenverCoder1/jct-discord-bot/commit/cd8b39c0b060cda935ec265e10ac8830de4ee6ca)
	- [x] Course management commands (1/6 complete)
	- [x] Email registry commands
	- [x] Error log command
	- [x] Join command
	- [x] Markdown command
	- [x] Ping command
	- [x] Search command
	- [x] XKCD commands
- [ ] Make sure everything is tested
- [x] Implement central exception handling (#369)
- [x] Fix `_EmptyEmbed` import error using `None` in `embedder.py` (See https://github.com/DenverCoder1/professor-vector-discord-bot/commit/6554d35ecad4484e29636259ac75720149143cea)

To contribute, feel free to make a PR targeting the [migrate-nextcord](https://github.com/DenverCoder1/jct-discord-bot/tree/migrate-nextcord) branch.

**Comment by avipars** [comment]
If its that easy as find and replace for the most part... I could probably do one or two modules over the weekend

**Comment by DenverCoder1** [comment]
The main thing left to do is converting slash commands that were using `discord-py-slash-command` to use `nextcord`

`discord-py-slash-command` used decorators for slash commands eg:

```py
@cog_ext.cog_subcommand(
	  base="base",
	  name="command",
	  description="Slash command",
	  guild_ids=[config.guild_id],
	  options=[
		    create_option(
			    name="arg",
			    description='Argument to receive',
			    option_type=SlashCommandOptionType.STRING,
			    required=True,
		    ),
	  ],
)
async def my_command(self, ctx: SlashContext, arg: str):
	await ctx.send("Hello!")
```

These need to be changed to instead use `@nextcord.slash_command` and SlashOptions as default parameters.

eg.

```py
@nextcord.slash_command(guild_ids=[config.guild_id])
async def base(interaction: nextcord.Interaction):
    pass


@base.subcommand(description="Subcommand 1")
async def command(interaction: nextcord.Interaction, arg: str=SlashOption(description='Argument to receive')):
    await interaction.send("Hello!")
```

The interfaces for SlashContext and [`nextcord.Interaction`](https://nextcord.readthedocs.io/en/stable/api.html?highlight=interaction#nextcord.Interaction) are different.

In the bot development channel, I've posted [a message](https://discord.com/channels/785207994429866014/796337618580668426/947630554294136852) with a quick explanation of interactions in nextcord.
